# Generated by Django 3.0.6 on 2020-05-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200525_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registeras',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient'), ('R', 'Receptionist'), ('HR', 'HR')], max_length=2),
        ),
    ]
